### ISSUE TITLE
Dependencies docs are not sufficient

### ISSUE THREAD

**Issue by TheLonelyGhost** [codebrainz/geany-zencoding#2]
**OS**: Ubuntu 11.10 (32-bit)

**Geany Version**:  geany 0.20 (built on Jul  1 2011 with GTK 2.24.5, GLib 2.29.8, GIO)

**Actions to Reproduce**:
1.  checked out git repository (2011-12-20)
2.  ran `cd geany-zencoding`, `chmod a+x autogen.sh`, and `autogen.sh`
3.  ran `./configure --prefix=$(dirname $(dirname $(which geany)))`

Expected:
"everything is okay, now run ./make and ./install"

Actual:
"
[...]
checking for gtk... no
configure: error: Package requirements (gtk+-2.0) were not met:

No package 'gtk+-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables gtk_CFLAGS
and gtk_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
"

**Comment by codebrainz** [comment]
Did you install the `libgtk2.0-dev` package?  This one has all the dev stuff needed to build against the GTK+ libraries (which is required to build Geany plugins).

**Comment by TheLonelyGhost** [comment]
I mistakenly thought I already had `geany-plugins` installed. After that, I ran into the same issue as [Issue #1](https://github.com/codebrainz/geany-zencoding/issues/1), which prompted me to install `python-dev`. After all dependencies were installed, I was able to run the plugin as per your instructions.

In your readme, I saw nothing to the effect of needing `geany-plugins` or `python-dev` installed, though the former now seems like common sense. I strongly suggest you update the readme to include them so further derps like me won't get tripped up by it.

_**Edit**: Just found the "Dependencies" near the bottom. Perhaps it should be relocated above "Installation" and include the package names?_

**Comment by codebrainz** [comment]
Heh, OK, I was going to tell you about it :)

I agree it's a good idea to move it up and elaborate on it a bit.  Maybe list the package names for popular distros even.  If you feel like making a patch, send me a pull request, otherwise I'll try to do it when I get a chance.

Thanks.

(I'm gonna re-open the issue so if I forget, next time I look I'll remember to do it :))

**Comment by codebrainz** [comment]
I fixed it a bit in ddee7a0d9351ef5cee7e979d8875a75673d648c7

**Comment by TheLonelyGhost** [comment]
Much appreciated! I'm still new to git (and completely unfamiliar with C) so helping isn't in the equation on my end. Fantastic job on this though!
