### ISSUE TITLE
Build dependencies missing

### ISSUE THREAD

**Issue by lorenzos** [codebrainz/geany-zencoding#5]
I think it will be great to add some dependencies needed for build the plugin in the _README.markdown_ file, where the _apt-get_ command line is given. I had to install additional packages in order to build it (and I came from a quasi-fresh installation of Ubuntu), `autoconf` and `libtool`. Also, `libgtk-2.0-dev` is mispelled I think: in my system the package is named `libgtk2.0-dev` So:

```
# apt-get install geany-plugins libgtk2.0-dev python-dev autoconf libtool
```

**Comment by codebrainz** [comment]
Fixed in 026cd851af95527b766ee3e73a0394ee164cc2bf

Thanks!
